###FOLLOW USER
POST http://localhost:8000/api/follow/68bb4d0293f5e32dcc72d4e2
###
POST http://localhost:8000/api/follow/68b92aeaf993cc197805622c
###
POST http://localhost:8000/api/follow/68bb4cf493f5e32dcc72d4dc
###
POST http://localhost:8000/api/follow/68bb4cf893f5e32dcc72d4de
###
POST http://localhost:8000/api/follow/68bb4cfe93f5e32dcc72d4e0


###UNFOLLOW USER
POST http://localhost:8000/api/unfollow/68b92aeaf993cc197805622c


###GET ALL FOLLOWS
GET http://localhost:8000/api/follow

###GET FOLLOWS OF USER
GET http://localhost:8000/api/user/follows/68b92aeaf993cc197805622c

###GET FOLLOWERS OF USER
GET http://localhost:8000/api/user/followers/68b92aeaf993cc197805622c