###GET ALL USERS
GET  http://localhost:8000/api/user 


###GET USER BY ID
GET  http://localhost:8000/api/user/68b92aeaf993cc197805622c



###CREATE NEW USER
POST http://localhost:8000/api/user 
Content-Type: application/json

{
    "username": "username5",
    "password": "12345678"
}

###UPDATE USER
PUT http://localhost:8000/api/user/68b92aeaf993cc197805622c 
Content-Type: application/json

{
    "username": "usernameUpdated2",
    "password": "1357911112"
}


###DELETE A USER
DELETE http://localhost:8000/api/user/68b92aeaf993cc197805622c 